# Generated by Django 5.1.5 on 2025-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOLPECAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jolpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='C:\\Users\\PASCHAL\\Desktop\\JOLPEC DJANGO\\JOLPECPROJECT\\static\\JOLPECLOGO.jpg')),
            ],
        ),
        migrations.DeleteModel(
            name='JolpecModel',
        ),
    ]
