# Generated by Django 5.1.5 on 2025-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOLPECAPP', '0002_jolpec_delete_jolpecmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Jolpec',
        ),
    ]
